### ISSUE TITLE
ulab firmware support for ESP32-WROOM-32 required.

### ISSUE THREAD

**Issue by hamza-712** [v923z/micropython-builder#11]
Hi,
Can you please include ESP32 support in micropython builder.

**Comment by zachmoshe** [comment]
I just submitted a PR that adds this: https://github.com/v923z/micropython-builder/pull/12
If you need to compile before @v923z gets to approve this, you can find a working version here: https://github.com/zachmoshe/micropython-builder/tree/testing
Just clone and run `./scripts/esp32/generic.sh` (or s3.sh for ESP32-S3)

**Comment by v923z** [comment]
@hamza-712 I think this is fixed via https://github.com/v923z/micropython-builder/pull/12.

**Comment by hamza-712** [comment]
thanks. its fixed

**Comment by v923z** [comment]
@hamza-712 As far as I understand, this issue has been fixed. If so, please, close it. Thanks!
